### ISSUE TITLE
Gradle sync failed: Could not resolve all dependencies for configuration ':ArcFaceDemo-master:debugRuntimeClasspath'.Could not determine artifacts for com.guo.android_extend:android-extend:1.0.5

### ISSUE THREAD

**Issue by tianzengyin** [asdfqwrasdf/ArcFaceDemo#101]
Gradle sync failed: Could not resolve all dependencies for configuration ':ArcFaceDemo-master:debugRuntimeClasspath'.
			Could not determine artifacts for com.guo.android_extend:android-extend:1.0.5

How to solve this problem, I can download it from the network for com.guo.android_extend:android-extend:1.0.5

**Comment by asdfqwrasdf** [comment]
please read the user guide first.
