### ISSUE TITLE
相机调用onPreview方法的时候   这个是在ui线程进行的  由于刷新的频率过快  导致阻塞ui线程

### ISSUE THREAD

**Issue by liu5241726** [asdfqwrasdf/ArcFaceDemo#102]
相机调用DetecterActivity的onPreview方法的时候，会在主线程进行。这是由于surfaceview调用该方法引起的，surface刷新的速度过快  会导致ui线程阻塞  导致其他得操作比如退出  返回一时间不能快速响应

**Comment by asdfqwrasdf** [comment]
参考demo 实现
