### ISSUE TITLE
想咨询

### ISSUE THREAD

**Issue by ylmyg** [asdfqwrasdf/ArcFaceDemo#105]
想问下，现在已经出了2.0版本的SDK，本demo是不是只支持导入1.2版本的SDK？

**Comment by asdfqwrasdf** [comment]
本demo只支持1.2， 2.0 变化较大，集成到本demo还有问题，正在沟通中

**Comment by asdfqwrasdf** [comment]
@ylmyg 2.0已经支持，可以看分支 [/dev_v2.0](https://github.com/asdfqwrasdf/ArcFaceDemo/tree/dev_v2.0)

**Comment by ylmyg** [comment]
收到
