### ISSUE TITLE
浆糊救急:android.app.Application cannot be cast to helloworld.skypan.com.facetry.Myapplication

### ISSUE THREAD

**Issue by ghost** [asdfqwrasdf/ArcFaceDemo#106]
在使用demo的时候运行时报错,排查了下发现是MainActivity这句话里面有问题:((Application)(MainActivity.this.getApplicationContext())),报错是android.app.Application cannot be cast to helloworld.skypan.com.facetry.Application,我想了下也对哎,一个父类怎么能转化为子类呢,请问大家都没遇到这个问题么,求问如何解决

**Comment by asdfqwrasdf** [comment]
修改demo 代码的时候需要注意下，导入的Application的包名。
