### ISSUE TITLE
不管是打开图片还是拍摄图片都提示   "没有检测到人脸，请换一张图片" (msg.arg1 == MSG_EVENT_NO_FACE)

### ISSUE THREAD

**Issue by chuntian119** [asdfqwrasdf/ArcFaceDemo#107]
C:\Users\Administrator>adb logcat | findstr "com.arcsoft.sdk_demo.RegisterActivity"
12-13 13:15:00.621  1149  2517 E ActivityTrigger: activityStartTrigger: not whiteListedcom.arcsoft.sdk_demo/com.arcsoft.sdk_demo.RegisterActivity/1
12-13 13:15:00.622  1149  2517 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.arcsoft.sdk_demo/com.arcsoft.sdk_demo.RegisterActivity/1
12-13 13:15:00.631  1149  2517 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.arcsoft.sdk_demo/com.arcsoft.sdk_demo.RegisterActivity/1
12-13 13:15:00.670 14189 14189 I class com.arcsoft.sdk_demo.RegisterActivity: getIntentData:/storage/emulated/0/Pictures/1544677758582.jpg
12-13 13:15:01.672 14189 21682 D class com.arcsoft.sdk_demo.RegisterActivity: convert ok!
12-13 13:15:01.672 14189 21682 D class com.arcsoft.sdk_demo.RegisterActivity: AFD_FSDK_InitialFaceEngine = 28677
12-13 13:15:01.672 14189 21682 D class com.arcsoft.sdk_demo.RegisterActivity: AFD_FSDK_GetVersion =null, 5
12-13 13:15:01.672 14189 21682 D class com.arcsoft.sdk_demo.RegisterActivity: AFD_FSDK_StillImageFaceDetection =5<0
12-13 13:15:01.686 14189 21682 D class com.arcsoft.sdk_demo.RegisterActivity: AFD_FSDK_UninitialFaceEngine =5

**Comment by asdfqwrasdf** [comment]
AFD_FSDK_InitialFaceEngine = 28677 错误码查一下：
MERR_FSDK_SYSTEM_VERSION_UNSUPPORTED 0x7005 不支持的系统版本
