### ISSUE TITLE
2.0的版本带有会体检测吗

### ISSUE THREAD

**Issue by sunmoonb** [asdfqwrasdf/ArcFaceDemo#108]
这个Demo2.0带有活体检测吗？

**Comment by asdfqwrasdf** [comment]
没有带活体检测，因为没有SDK。

**Comment by sunmoonb** [comment]
他官网不是才开放一个2.0的Android SDK带有活体检测的吗

**Comment by asdfqwrasdf** [comment]
不是企业用户申请不到活体检测SDK

**Comment by sunmoonb** [comment]
不是这样，2.0版本的人脸识别SDK Android平台带有活体检测，只需要个人认证就可以申请，你可以去官网看看

**Comment by asdfqwrasdf** [comment]
> 不是这样，2.0版本的人脸识别SDK Android平台带有活体检测，只需要个人认证就可以申请，你可以去官网看看
已经确认过：

仅企业认证用户可使用~

企业认证用户拥有最全的产品库和最多的特权 

立即认证→
----
或者你可以提供给SDK的话，我也可以加进去。

**Comment by sunmoonb** [comment]
你可以留个联系方式 我联系你

**Comment by sunmoonb** [comment]
我记得当时我在申请ArcFace 2.0 Android2.0版本SDK时只用进行个人认证就可以的，只有在申请活体检测V1.2 SDK时才需要企业认证，不知道现在是不是改了

**Comment by asdfqwrasdf** [comment]
现在确实需要企业认证，如有SDK和KEY可以发到此邮箱：
409467142@qq.com

**Comment by sunmoonb** [comment]
明天有时间，发给你




在2018年12月27日 17:28，asdfqwrasdf 写道：

现在确实需要企业认证，如有SDK和KEY可以发到此邮箱：
409467142@qq.com
