### ISSUE TITLE
sdk_domo keeps stopping

### ISSUE THREAD

**Issue by kaniel-outis** [asdfqwrasdf/ArcFaceDemo#113]
sdk_domo keeps stopping?
when run app in avd.

**Comment by asdfqwrasdf** [comment]
Read the user guide first.

**Comment by kaniel-outis** [comment]
so how to use the camera in desktop.

**Comment by asdfqwrasdf** [comment]
> so how to use the camera in desktop.

this project is support android os only.
we already tested the app in avd(android5.1 armeabi-v7a), it's worked well.
if it's not working well in your device, please check the error log first.

by the way.
In this project, we use the getExternalCacheDir API to get the path to write face database.
so the avd should have virtual SDcard, or you can change this path to other writable place.
