### ISSUE TITLE
速度识别很慢.

### ISSUE THREAD

**Issue by hhhaiai** [asdfqwrasdf/ArcFaceDemo#12]
对焦好慢  哪里设置能优化?

**Comment by asdfqwrasdf** [comment]
@hhhaiai 如果是对焦慢，属于手机系统问题，demo里只是调用了系统的对焦，如何优化自行斟酌。
如果是识别速度慢，换个骁龙835的手机速度会快很多，目前版本SDK CPU性能暂时就这样了。

**Comment by hhhaiai** [comment]
好的 多谢
