### ISSUE TITLE
1:1  和1:N有什么区别? 如何跨设备验证?

### ISSUE THREAD

**Issue by hhhaiai** [asdfqwrasdf/ArcFaceDemo#13]
您好:
   试用贵方的1:1安卓 demo 运行起来,可以工作,    如何和其他平台的打通?   安卓认证 IOS 也可以识别,有办法交互数据吗?
    
   1:1SDK 和1:N 的SDK有什么区别啊

**Comment by asdfqwrasdf** [comment]
官方SDK通过API提取的特征值，在android ios windows linux上都是可以共用的。
交互数据的方案请自行选择。

1：1 验证你是不是你
1：N 从一堆人里找到你
具体请参考官方解释。
