### ISSUE TITLE
1：N检索的时候，怎样才能更好的优化速度呢？

### ISSUE THREAD

**Issue by wait1988** [asdfqwrasdf/ArcFaceDemo#15]
当人脸特征库在10以下的时候，单人识别速度可以，但是当人脸特征在100左右的时候，速度就下降很多，应该从哪些方面来改进代码呢

**Comment by gqjjqg** [comment]
@wait1988 100左右就下降很多，说明硬件配置偏低。代码改不了。

**Comment by asdfqwrasdf** [comment]
@wait1988 接口上的优化估计只能考官方改善，应用上的优化，可以试试多线程
