### ISSUE TITLE
如何设置镜头识别显示的大小？

### ISSUE THREAD

**Issue by heweiquan** [asdfqwrasdf/ArcFaceDemo#18]
![image](https://user-images.githubusercontent.com/13057762/33105964-d25dcd34-cf6a-11e7-87b4-be86c8731302.png)
我是直接操作demo的activity_camera.xml来修改的。明明已经设置了match_parent也无效！！！
![image](https://user-images.githubusercontent.com/13057762/33105978-eee9138c-cf6a-11e7-8368-2e7e9e50ab1e.png)
这里也在代码设置了camera的大小了，感觉也无效！
![image](https://user-images.githubusercontent.com/13057762/33106035-3bfa4bc8-cf6b-11e7-903f-a47d7557a8e4.png)
![image](https://user-images.githubusercontent.com/13057762/33106042-451782de-cf6b-11e7-85db-2175fce77ba0.png)
求解。如何把第一个图的蓝色部分也填充掉？

**Comment by heweiquan** [comment]
追加一下，运行原来的demo，感觉识别镜头控件显示的大小也不是match_parent的！！！
![image](https://user-images.githubusercontent.com/13057762/33106206-f59a8890-cf6b-11e7-9cdd-b683eeb8c58b.png)

demo的activity_camera.xml：
![image](https://user-images.githubusercontent.com/13057762/33106180-e69e6eba-cf6b-11e7-9c6e-46116eb2bc14.png)

**Comment by gqjjqg** [comment]
CameraGLSurfaceView作为一个显示相机预览的view，按相机预览长宽比例忠实显示到屏幕上是比较正常的逻辑，如非要不按比例来，请查看此类源码自行修改。如果不熟悉代码，不建议你直接改demo。

**Comment by asdfqwrasdf** [comment]
@heweiquan 建议 不调用下面的代码，自己做preview的渲染，或者用另外一个surfaceview渲染即可解决。
```java 
mSurfaceView.setupGLSurafceView(mGLSurfaceView, true, mCameraMirror, mCameraRotate); 
```

**Comment by willims** [comment]
相机设置预览参数，是要看当前相机支持哪些比例，并不是随意设置进去的

**Comment by heweiquan** [comment]
好的。我知道怎么改了3Q！

**Comment by XinYou** [comment]
碰到同样的问题，楼主是怎么改的，分享下

**Comment by HiGitHubWorld** [comment]
请问是如何解决
