### ISSUE TITLE
出现如下报错

### ISSUE THREAD

**Issue by imaginefish** [asdfqwrasdf/ArcFaceDemo#19]
Error:Execution failed for task ':ArcFaceDemo-master:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

**Comment by gqjjqg** [comment]
看样子是编译问题，请严格按照readme操作

**Comment by asdfqwrasdf** [comment]
像是gradle有问题
