### ISSUE TITLE
demo中预览视频流总是循转了90度，在setupCamera()中调用Camera.setDisplayOrientation()没有效果

### ISSUE THREAD

**Issue by blackbridcn** [asdfqwrasdf/ArcFaceDemo#20]
demo中预览视频流总是循转了90度，在setupCamera()中调用Camera.setDisplayOrientation()没有效果

**Comment by asdfqwrasdf** [comment]
渲染是另外定制了，cameraglsurfaceview，和camera无关了，对这个view设置就可以。话说回来，不熟悉代码，不建议直接改demo

**Comment by blackbridcn** [comment]
呃呃呃，丢人了，原来是有设置参数的，就是没多想就以为是Camera的没有设置方向……

**Comment by kouhengsheng** [comment]
请问一下是怎么设置camera的，方不方便展示一下代码，demo里面的DetecterActivity在手机上也是横屏的，旋转了90。我把activity的oreatation属性改成横屏或者竖屏都不管用。请大神指教一下。
