### ISSUE TITLE
CameraGLSurfaceView 用作相机预览时无法全屏，不知能解决吗？

### ISSUE THREAD

**Issue by synchroni** [asdfqwrasdf/ArcFaceDemo#26]
CameraGLSurfaceView 用作相机预览时无法全屏，不知能解决吗？ 它里面有做有操作，怎么给Camera.setPreviewSize 都没用。。。

**Comment by asdfqwrasdf** [comment]
参考 #18

**Comment by heweiquan** [comment]
@synchroni 我之前通过查阅资料，发现通过下载并修改android-extend源码，找到com.guo.android_extend.widget.CameraSurfaceView，进行如下修改：
![image](https://user-images.githubusercontent.com/13057762/34427028-360f6ba6-ec78-11e7-9794-006cf3889d3f.png)
不过这样相机预览确实全屏了，但是它会使得获取到的抓拍图像变形。
