### ISSUE TITLE
注册人脸失败

### ISSUE THREAD

**Issue by FlyingSnow2211** [asdfqwrasdf/ArcFaceDemo#27]
FD初始化失败，错误码28677！
人脸注册失败，没有检测到人脸，这是为什么

**Comment by asdfqwrasdf** [comment]
仔细阅读readme

**Comment by FlyingSnow2211** [comment]
点击注册后就直接拍照，拍照完成点击储存直接Toast没有检测到人脸！
我真没发现readme哪里提到这个问题解决方案了，请大神明示！
