### ISSUE TITLE
请教一下AFD_FSDK_StillImageFaceDetection方法

### ISSUE THREAD

**Issue by GirlFriendNotFind** [asdfqwrasdf/ArcFaceDemo#31]
文档说传进AFD_FSDK_StillImageFaceDetection方法中的height不能为奇数，我对height做一个奇数判断，如果是奇数就加1，结果就会报参数错误，是因为不能乱改图像数据吧，是不是判断如果是奇数就不要调用检测API了直接提示图像不合法？
int mPicBitmapHeight = mPicBitmap.getHeight();
if(mPicBitmapHeight是奇数){mPicBitmapHeight = mPicBitmapHeight+1; }
 err  = engine.AFD_FSDK_StillImageFaceDetection(data, mPicBitmap.getWidth(), mPicBitmapHeight, AFD_FSDKEngine.CP_PAF_NV21, result);

**Comment by GirlFriendNotFind** [comment]
还有录入人脸只能一张张检测识别保存吗(⊙o⊙)？？

**Comment by GirlFriendNotFind** [comment]
error = engine.AFR_FSDK_FacePairMatching(result, face, score);getCode返回的错误码是73733。。。。

**Comment by GirlFriendNotFind** [comment]
检测识别操作，获取人脸对比的相似度值的时候报错误码为 73733特征信息版本不匹配，我下载的sdk都是1.1压缩包里的怎么会版本不对呢？？

**Comment by asdfqwrasdf** [comment]
sdk的问题建议论坛咨询
