### ISSUE TITLE
Another bug in PermissionAcitivity.java

### ISSUE THREAD

**Issue by overlook1234** [asdfqwrasdf/ArcFaceDemo#34]
`Application app = (Application) PermissionAcitivity.this.getApplicationContext();`

should be

`Application app = (Application) PermissionAcitivity.this.getApplication();`

**Comment by asdfqwrasdf** [comment]
Actually these two function return the same object.
In the demo, both methods can be used normally.

**Comment by overlook1234** [comment]
The code works fine when I use your sample.  But it throws exceptions when I try to integrate it into my project.
