### ISSUE TITLE
demo运行完，“注册”没问题，但是“检测识别”打开相机，界面一片绿，显示不出正常的画面。

### ISSUE THREAD

**Issue by cpq0329** [asdfqwrasdf/ArcFaceDemo#38]
楼主你好，昨天试了下你的sdk,还是有点问题，key那些都注册了。检测识别人脸，后置，前置相机打开，都是一片绿的页面。没有出现正常的画面。我测试的机子安卓版本是6.0.1的。不知道这个是什么原因导致的？

**Comment by asdfqwrasdf** [comment]
附上log看看

**Comment by cpq0329** [comment]
这是首页的log.底下有打开摄像头的。。但是没有出现异常，就是画面是先黑了一下然后就都是绿的。
01-12 11:15:04.484 21569-21569/? E/libprocessgroup: failed to make and chown /acct/uid_10056: Read-only file system
01-12 11:15:04.484 21569-21569/? W/Zygote: createProcessGroup failed, kernel missing CONFIG_CGROUP_CPUACCT?
01-12 11:15:04.491 21569-21569/? I/art: Late-enabling -Xcheck:jni
01-12 11:15:04.491 21569-21569/? I/art: Late-enabling JIT
01-12 11:15:04.521 21569-21569/? I/art: JIT created with code_cache_capacity=2MB compile_threshold=1000
01-12 11:15:04.780 21569-21569/com.arcsoft.sdk_demo D/class com.arcsoft.sdk_demo.FaceDB: AFR_FSDK_GetVersion=1.1.0.42
01-12 11:15:04.837 21569-21584/com.arcsoft.sdk_demo I/art: Background sticky concurrent mark sweep GC freed 4613(262KB) AllocSpace objects, 0(0B) LOS objects, 35% free, 1473KB/2MB, paused 9.240ms total 26.702ms
01-12 11:15:04.855 21569-21602/com.arcsoft.sdk_demo D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
01-12 11:15:04.892 21569-21603/com.arcsoft.sdk_demo D/class com.arcsoft.sdk_demo.FaceDB: load name:chen's face feature data.
01-12 11:15:04.898 21569-21603/com.arcsoft.sdk_demo D/class com.arcsoft.sdk_demo.FaceDB: load name: size = 1
01-12 11:15:04.985 21569-21602/com.arcsoft.sdk_demo D/libEGL: loaded /vendor/lib/egl/libEGL_POWERVR_SGX544_115.so
01-12 11:15:05.038 21569-21602/com.arcsoft.sdk_demo D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_POWERVR_SGX544_115.so
01-12 11:15:05.063 21569-21602/com.arcsoft.sdk_demo D/libEGL: loaded /vendor/lib/egl/libGLESv2_POWERVR_SGX544_115.so
01-12 11:15:05.093 21569-21602/com.arcsoft.sdk_demo I/IMGSRV: Dram size is 1003 MB
01-12 11:15:05.093 21569-21602/com.arcsoft.sdk_demo I/IMGSRV: Secure level is 1
01-12 11:15:05.094 21569-21602/com.arcsoft.sdk_demo I/IMGSRV: Allocate 4096 Bytes uncached memory via ion heap type DMA successfully, iUsage = 0x10000000
01-12 11:15:05.095 21569-21602/com.arcsoft.sdk_demo I/IMGSRV: Dram size is 1003 MB
01-12 11:15:05.095 21569-21602/com.arcsoft.sdk_demo I/IMGSRV: Secure level is 1
01-12 11:15:05.095 21569-21602/com.arcsoft.sdk_demo I/OpenGLRenderer: Initialized EGL, version 1.4
01-12 11:15:05.095 21569-21602/com.arcsoft.sdk_demo W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
========================================
这是打开后置相机的。
01-12 11:20:45.687 21569-21569/com.arcsoft.sdk_demo W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
01-12 11:20:45.820 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: AFT_FSDK_InitialFaceEngine =0
01-12 11:20:45.824 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: AFT_FSDK_GetVersion:1.1.0.42,0
01-12 11:20:45.893 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: ASAE_FSDK_InitAgeEngine =0
01-12 11:20:45.897 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: ASAE_FSDK_GetVersion:1.1.0.44,0
01-12 11:20:45.959 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: ASGE_FSDK_InitgGenderEngine =0
01-12 11:20:45.962 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: ASGE_FSDK_GetVersion:1.1.0.44,0
01-12 11:20:45.993 21569-24606/com.arcsoft.sdk_demo D/DetecterActivity: AFR_FSDK_InitialEngine = 0
01-12 11:20:45.998 21569-24606/com.arcsoft.sdk_demo D/DetecterActivity: FR=1.1.0.42,0
01-12 11:20:46.164 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: SIZE:640x480
01-12 11:20:46.164 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: FORMAT:17
01-12 11:20:46.164 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: FORMAT:842094169
01-12 11:20:46.164 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: T:
01-12 11:20:46.165 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: V=30000
01-12 11:20:46.165 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: V=30000
01-12 11:20:46.165 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: T:
01-12 11:20:46.165 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: V=5000
01-12 11:20:46.165 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: V=60000
01-12 11:20:46.186 21569-21569/com.arcsoft.sdk_demo D/CameraSurfaceView: preview size = 1280,960
01-12 11:20:46.375 21569-24550/com.arcsoft.sdk_demo I/ATC.: image.so JNI_OnLoad
01-12 11:20:46.376 21569-24550/com.arcsoft.sdk_demo D/ATC.: glesInit() <--- format = 2050
01-12 11:20:46.376 21569-24550/com.arcsoft.sdk_demo D/ATC.: glGetShaderiv called  shader = 70001 GL_INVALID_ENUM = 1280 GL_INVALID_OPERATION = 1282
01-12 11:20:46.376 21569-24550/com.arcsoft.sdk_demo D/ATC.: glGetShaderiv called compiled = 1, shader = 70001
01-12 11:20:46.377 21569-24550/com.arcsoft.sdk_demo D/ATC.: glGetShaderiv called  shader = 140002 GL_INVALID_ENUM = 1280 GL_INVALID_OPERATION = 1282
01-12 11:20:46.377 21569-24550/com.arcsoft.sdk_demo D/ATC.: glGetShaderiv called compiled = 1, shader = 140002
01-12 11:20:46.377 21569-24550/com.arcsoft.sdk_demo D/ATC.: glAttachShader
01-12 11:20:46.378 21569-24550/com.arcsoft.sdk_demo D/ATC.: glBindAttribLocation
01-12 11:20:46.378 21569-24550/com.arcsoft.sdk_demo D/ATC.: glLinkProgram
01-12 11:20:46.378 21569-24550/com.arcsoft.sdk_demo D/ATC.: glGenTextures
01-12 11:20:46.378 21569-24550/com.arcsoft.sdk_demo D/ATC.: VBO
01-12 11:20:46.378 21569-24550/com.arcsoft.sdk_demo D/ATC.: glesInit() --->
01-12 11:20:46.378 21569-24550/com.arcsoft.sdk_demo D/ATC.: glesInit() <--- format = 2050
01-12 11:20:46.378 21569-24550/com.arcsoft.sdk_demo D/ATC.: glGetShaderiv called  shader = 280004 GL_INVALID_ENUM = 1280 GL_INVALID_OPERATION = 1282
01-12 11:20:46.378 21569-24550/com.arcsoft.sdk_demo D/ATC.: glGetShaderiv called compiled = 1, shader = 280004
01-12 11:20:46.378 21569-24550/com.arcsoft.sdk_demo D/ATC.: glGetShaderiv called  shader = 350005 GL_INVALID_ENUM = 1280 GL_INVALID_OPERATION = 1282
01-12 11:20:46.379 21569-24550/com.arcsoft.sdk_demo D/ATC.: glGetShaderiv called compiled = 1, shader = 350005
01-12 11:20:46.379 21569-24550/com.arcsoft.sdk_demo D/ATC.: glLinkProgram
01-12 11:20:46.379 21569-24550/com.arcsoft.sdk_demo D/ATC.: glesInit() --->
01-12 11:20:46.379 21569-24550/com.arcsoft.sdk_demo D/ATC.: glesChanged(1080, 1832) <---
01-12 11:20:46.379 21569-24550/com.arcsoft.sdk_demo D/ATC.: glesChanged() --->
01-12 11:20:46.379 21569-24550/com.arcsoft.sdk_demo D/ATC.: GLChangedAngle(0, 90) <---
01-12 11:20:46.379 21569-24550/com.arcsoft.sdk_demo D/ATC.: GLChangedAngle() --->
01-12 11:20:46.456 21569-24550/com.arcsoft.sdk_demo D/ATC.: glesChanged(1080, 1440) <---
01-12 11:20:46.456 21569-24550/com.arcsoft.sdk_demo D/ATC.: glesChanged() --->
01-12 11:20:46.456 21569-24550/com.arcsoft.sdk_demo D/ATC.: GLChangedAngle(0, 90) <---
01-12 11:20:46.456 21569-24550/com.arcsoft.sdk_demo D/ATC.: GLChangedAngle() --->
01-12 11:20:47.536 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: AFT_FSDK_FaceFeatureDetect =0
01-12 11:20:47.536 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: Face=0
01-12 11:20:47.571 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: AFT_FSDK_FaceFeatureDetect =0
01-12 11:20:47.571 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: Face=0
01-12 11:20:47.674 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: AFT_FSDK_FaceFeatureDetect =0
01-12 11:20:47.674 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: Face=0
01-12 11:20:47.722 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: AFT_FSDK_FaceFeatureDetect =0
01-12 11:20:47.722 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: Face=0
01-12 11:20:47.762 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: AFT_FSDK_FaceFeatureDetect =0
01-12 11:20:47.762 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: Face=0
01-12 11:20:47.802 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: AFT_FSDK_FaceFeatureDetect =0
01-12 11:20:47.802 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: Face=0
01-12 11:20:47.841 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: AFT_FSDK_FaceFeatureDetect =0
01-12 11:20:47.841 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: Face=0
01-12 11:20:47.877 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: AFT_FSDK_FaceFeatureDetect =0
01-12 11:20:47.877 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: Face=0
01-12 11:20:47.924 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: AFT_FSDK_FaceFeatureDetect =0
01-12 11:20:47.924 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: Face=0
01-12 11:20:47.965 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: AFT_FSDK_FaceFeatureDetect =0
01-12 11:20:47.965 21569-21569/com.arcsoft.sdk_demo D/DetecterActivity: Face=0
01-12 11:20:47.993 21569-21569/com.arcsoft.sdk_demo E/FrameHelper: FPS = 20

**Comment by asdfqwrasdf** [comment]
log上看后置应该是正常的，系统相机打开正常吗？

**Comment by cpq0329** [comment]
系统相机打开是正常的，我这边画面是倒的，这个是刷机固件的问题，但是应该不影响把。而且你那个demo的人脸注册也是可以的，就是画面是倒的，得旋转下。就是不知道为什么 检测识别打开相机就不行了。这边还有个log一直打印 1-12 11:33:44.665 218-456/? E/CallbackNotifier: error size, 1280x720 -> 1280x960
01-12 11:33:44.697 218-456/? E/CallbackNotifier: error size, 1280x720 -> 1280x960
01-12 11:33:44.749 218-456/? E/CallbackNotifier: error size, 1280x720 -> 1280x960
01-12 11:33:44.819 218-456/? E/CallbackNotifier: error size, 1280x720 -> 1280x960

**Comment by cpq0329** [comment]
可以了 应该是这个屏幕大小问题 我改成1280x720 画面能出来了 就是页面是倒着的。
