### ISSUE TITLE
不能使用框架com.facebook.fresco:fresco:0.9.0

### ISSUE THREAD

**Issue by hzhdeine** [asdfqwrasdf/ArcFaceDemo#44]
不使用框架com.facebook.fresco:fresco:0.9.0时能使用，使用框架com.facebook.fresco:fresco:0.9.0时显示异常提示：java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.gmcx.upload-1/base.apk", zip file "/data/app/com.gmcx.upload-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.gmcx.upload-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.gmcx.upload-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.gmcx.upload-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.gmcx.upload-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.gmcx.upload-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.gmcx.upload-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.gmcx.upload-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.gmcx.upload-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.gmcx.upload-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.gmcx.upload-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.gmcx.upload-1/lib/arm64, /system/fake-libs64, /data/app/com.gmcx.upload-1/base.apk!/lib/arm64-v8a, /data/app/com.gmcx.upload-1/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.gmcx.upload-1/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.gmcx.upload-1/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.gmcx.upload-1/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.gmcx.upload-1/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.gmcx.upload-1/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.gmcx.upload-1/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.gmcx.upload-1/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.gmcx.upload-1/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.gmcx.upload-1/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.gmcx.upload-1/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]] couldn't find "libmpbase.so"

**Comment by asdfqwrasdf** [comment]
sdk没arm64的库，复制一个到ARM64下说不定可以。
