### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by 840631861** [asdfqwrasdf/ArcFaceDemo#47]
原来用的手机都可以正常运行，但用到定制的android设备，闪退；只要布局里用CameraGLSurfaceView就闪退，跟断点发现正常运行时都会运行CameraGLSurfaceView中的setImageConfig，闪退时不会进此函数

**Comment by 840631861** [comment]
更正：CameraSurfaceView的mCamera = mOnCameraListener.setupCamera();报异常 Fail to connect to camera service

**Comment by asdfqwrasdf** [comment]
请提供更多信息或者log。
camera service 连接不上的话，属于系统问题，可以检查一下权限等。

**Comment by 840631861** [comment]
感谢回复，找到问题了，是设备问题，虽然摄像头在前面却要调用后摄像头
