### ISSUE TITLE
usb

### ISSUE THREAD

**Issue by yangxian10** [asdfqwrasdf/ArcFaceDemo#49]
使用外置usb摄像头做人脸检测，分辨率640*480（720*960）都很难检测出人脸，用android自带前置后置摄像头都可以很好的检测出人脸，是什么原因呢

**Comment by asdfqwrasdf** [comment]
USB 摄像头的ISP处理不像手机一样追求图像质量，经常发生3A不准导致的各种问题，比如偏色、失焦、欠曝等。个人猜测应该会对检测率有影响，这个属于SDK的问题，和demo无关，请反馈官方论坛。
