### ISSUE TITLE
现场照片与二代证小照片（102*126）进行1：1比对，分值偏低！！

### ISSUE THREAD

**Issue by loongsun** [asdfqwrasdf/ArcFaceDemo#5]
你好，请问贵公司的免费算法在对二代证小照片（人证统一验证）方面支持的怎么样？可不可以应用到市场上？

**Comment by asdfqwrasdf** [comment]
@loongsun 本身SDK分值系统就是比较保守的，偏低应该属于正常情况。支持的如何您自己测试一下就清楚了，SDK永久免费，可放心应用。非Demo相关的issue，请联系官方客服或者商务。官方SDK交流 QQ群:482124810
