### ISSUE TITLE
求解

### ISSUE THREAD

**Issue by AAAAWen** [asdfqwrasdf/ArcFaceDemo#50]
在AS中导入这个项目后，会出现Error:(31, 35) 错误: 程序包com.arcsoft.facerecognition不存在。请问这样该怎么解决呢？demo里面我找不到libs文件夹这该怎么解决？原谅我是个小白，在此先说声感谢！

**Comment by asdfqwrasdf** [comment]
请按照readme操作，找不到libs就创建一个。
