### ISSUE TITLE
ArcFaceDemo-master:transformDexArchiveWithExternalLibsDexMergerForDebug

### ISSUE THREAD

**Issue by ELEVENEV** [asdfqwrasdf/ArcFaceDemo#51]
导入了libs包以后buildAPK报错，请教是怎么回事，是否遇到过类似的问题，
我使用的是
    Android Studio 3.0
    compileSdkVersion 25
    buildToolsVersion "26.0.2"

![image.png](http://upload-images.jianshu.io/upload_images/5916479-53a97b5bd3edd558.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by asdfqwrasdf** [comment]
libs下的android_extends.jar 是用脚本网络下载，所以要删掉，否则有冲突
