### ISSUE TITLE
Android 7.0加载so异常

### ISSUE THREAD

**Issue by awen2007** [asdfqwrasdf/ArcFaceDemo#53]
java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib/libmpbase.so" needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace "classloader-namespace"

请问这个这么解决？？？

**Comment by asdfqwrasdf** [comment]
请具体描述demo使用背景。

**Comment by awen2007** [comment]
好啦，我指定so的cpu类型就可以了armeabi
