### ISSUE TITLE
虹软 SDK 是不是暂时不支持 Android 8.1 设备？

### ISSUE THREAD

**Issue by hayukleung** [asdfqwrasdf/ArcFaceDemo#54]
如题，我在 Android 8.1 设备上运行，注册人脸时抛出错误代码 MERR_FSDK_SYSTEM_VERSION_UNSUPPORTED，code 的返回值为 28677，是不是不支持 Android 8.1？

**Comment by asdfqwrasdf** [comment]
请反馈官方论坛
