### ISSUE TITLE
I didn't find the lib in your original document! Is there any dll document missing in your zip?

### ISSUE THREAD

**Issue by ZTShao** [asdfqwrasdf/ArcFaceDemo#56]
Sorry, I didn't find any libs in your documents, so where shall I put the arcface libs? Still, when I was trying to debug the whole project, it suggestes that there were so many functions and documents missing. How may I deal with this problem？ Hope you can help me ! 
Thanks!

**Comment by asdfqwrasdf** [comment]
please read the user guide first!
