### ISSUE TITLE
帮帮我！！求求你了！

### ISSUE THREAD

**Issue by ZTShao** [asdfqwrasdf/ArcFaceDemo#57]
![cuo lq 1 20 z x2kgu6](https://user-images.githubusercontent.com/37725899/38006647-8be03754-3278-11e8-881a-fa59abb11731.png)
直接编译都通过了  就是连上真机调试出BUG  而且不懂这个怎么改  求助！！！
Error:Execution failed for task ':ArcFaceDemo-master:transformClassesWithExtractJarsForDebug'.
> java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $

**Comment by asdfqwrasdf** [comment]
使用抽取 jar 转换类以进行调试 的任务失败了。 来自bing翻译。
不属于demo 的 bug，恕难解决。

**Comment by huyawen** [comment]
看到这个题目  忍不住 进来看看
