### ISSUE TITLE
导入报错

### ISSUE THREAD

**Issue by lzp5579** [asdfqwrasdf/ArcFaceDemo#59]
Information:Gradle tasks [clean, :ArcFaceDemo-master:generateDebugSources, :ArcFaceDemo-master:generateDebugAndroidTestSources, :ArcFaceDemo-master:mockableAndroidJar]
Error:Could not resolve all files for configuration ':ArcFaceDemo-master:debugAndroidTestRuntimeClasspath'.
> Failed to transform file 'facedetection.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file E:\workspace\face\ArcFaceDemo-master\ArcFaceDemo-master\libs\facedetection.jar does not exist.
> Failed to transform file 'facerecognition.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file E:\workspace\face\ArcFaceDemo-master\ArcFaceDemo-master\libs\facerecognition.jar does not exist.
> Failed to transform file 'facetracking.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file E:\workspace\face\ArcFaceDemo-master\ArcFaceDemo-master\libs\facetracking.jar does not exist.
> Failed to transform file 'ageestimation.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file E:\workspace\face\ArcFaceDemo-master\ArcFaceDemo-master\libs\ageestimation.jar does not exist.
> Failed to transform file 'genderestimation.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file E:\workspace\face\ArcFaceDemo-master\ArcFaceDemo-master\libs\genderestimation.jar does not exist.

**Comment by Haojingxuan** [comment]
Error:Could not resolve all files for configuration ':ArcFaceDemo-master:debugAndroidTestRuntimeClasspath'.
> Failed to transform file 'facedetection.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file D:\Face\ArcFaceDemo-master\ArcFaceDemo-master\libs\facedetection.jar does not exist.
> Failed to transform file 'facerecognition.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file D:\Face\ArcFaceDemo-master\ArcFaceDemo-master\libs\facerecognition.jar does not exist.
> Failed to transform file 'facetracking.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file D:\Face\ArcFaceDemo-master\ArcFaceDemo-master\libs\facetracking.jar does not exist.
> Failed to transform file 'ageestimation.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file D:\Face\ArcFaceDemo-master\ArcFaceDemo-master\libs\ageestimation.jar does not exist.
> Failed to transform file 'genderestimation.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file D:\Face\ArcFaceDemo-master\ArcFaceDemo-master\libs\genderestimation.jar does not exist.
