### ISSUE TITLE
修改成调用前置摄像头后，预览时候图像倒置，按照网上的资料无法实现正常的显示，还是倒置

### ISSUE THREAD

**Issue by tianpengyuanshuai** [asdfqwrasdf/ArcFaceDemo#6]
修改成调用前置摄像头后，预览时候图像倒置，自己给自己采集照片比对不放，希望能有一个设置为前置摄像头预览的功能和后置摄像头预览的功能，图像不要倒置。

按照网上的资料无法实现正常的显示，还是倒置，请看：
http://www.jianshu.com/p/1513134733d0

**Comment by asdfqwrasdf** [comment]
@tianpengyuanshuai 不知道您是怎么修改的，我为demo增加了开启前置的选项，您重新check一下。

**Comment by tianpengyuanshuai** [comment]
谢谢
