### ISSUE TITLE
导入Android-extend 作为依赖时报错

### ISSUE THREAD

**Issue by jluF** [asdfqwrasdf/ArcFaceDemo#60]
Error:Could not get unknown property 'PROJ_GROUP' for project ':android-extend' of type org.gradle.api.Project.
我将这个module作为依赖导入，可是却一直报这个错，这个PROJ_GROUP是bintrary.gradle的一个属性

**Comment by asdfqwrasdf** [comment]
如不熟悉，简单处理 删除bintrary.gradle即可
