### ISSUE TITLE
ArcFace

### ISSUE THREAD

**Issue by hhmuseng** [asdfqwrasdf/ArcFaceDemo#61]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.arcsoft.sdk_demo-98Nw7558fKIWwqD0hVH5SA==/base.apk", zip file "/data/app/com.arcsoft.sdk_demo-98Nw7558fKIWwqD0hVH5SA==/split_lib_dependencies_apk.apk", zip file "/data/app/com.arcsoft.sdk_demo-98Nw7558fKIWwqD0hVH5SA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.arcsoft.sdk_demo-98Nw7558fKIWwqD0hVH5SA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.arcsoft.sdk_demo-98Nw7558fKIWwqD0hVH5SA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.arcsoft.sdk_demo-98Nw7558fKIWwqD0hVH5SA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.arcsoft.sdk_demo-98Nw7558fKIWwqD0hVH5SA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.arcsoft.sdk_demo-98Nw7558fKIWwqD0hVH5SA==/split_lib_slice_5_apk.apk", zip file "/data/app/com.arcsoft.sdk_demo-98Nw7558fKIWwqD0hVH5SA==/split_lib_slice_6_apk.apk", zip file "/data/app/com.arcsoft.sdk_demo-98Nw7558fKIWwqD0hVH5SA==/split_lib_slice_7_apk.apk", zip file "/data/app/com.arcsoft.sdk_demo-98Nw7558fKIWwqD0hVH5SA==/split_lib_slice_8_apk.apk", zip file "/data/app/com.arcsoft.sdk_demo-98Nw7558fKIWwqD0hVH5SA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.arcsoft.sdk_demo-98Nw7558fKIWwqD0hVH5SA==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libmpbase.so"

**Comment by hhmuseng** [comment]
虹软android人脸识别demo报错

**Comment by asdfqwrasdf** [comment]
请按readme操作
