### ISSUE TITLE
is this : ArcFace: Additive Angular Margin Loss for Deep Face Recognition

### ISSUE THREAD

**Issue by MyraBaba** [asdfqwrasdf/ArcFaceDemo#66]

**Comment by asdfqwrasdf** [comment]
before report
please check the closed issues.

issue report format
a.error info:log，input image，core stack, etc...
b.device info:cpu, memory, device name, etc...
c.os info:OS version, API leve,etc...
d.detial :which step,how to recurrence,etc...
