### ISSUE TITLE
demo 运行状态返回吗是5

### ISSUE THREAD

**Issue by frankie9527** [asdfqwrasdf/ArcFaceDemo#70]
1、demo没jar 运行不起来
2、加了jar 并添加了相应想appkey  但是运行起来 errorCode 一直是5
   public static final int MERR_BAD_STATE = 5;
请问怎么解决？

**Comment by frankie9527** [comment]
AFT_FSDKEngine aftEngine = new AFT_FSDKEngine();
        AFT_FSDKError err = aftEngine.AFT_FSDK_InitialFaceEngine(APPID, FTKEY, AFT_FSDKEngine.AFT_OPF_0_HIGHER_EXT, 16, 5);
err.getCode() =28676

  err = aftEngine.AFT_FSDK_GetVersion(atfVersion);
err.getCode()=5

已解决！

**Comment by asdfqwrasdf** [comment]
初始化已经报错，先解决28676的错误。
