### ISSUE TITLE
注册人脸成功后，检测识别选择相机崩溃

### ISSUE THREAD

**Issue by gzjck** [asdfqwrasdf/ArcFaceDemo#71]
如题，无论是前置还是后置都崩溃

**Comment by sjhsjh** [comment]
发现bug一个：操作步骤：检测识别--切换摄像头--回到桌面--回到应用--摄像头反转了
解决办法：DetecterActivity的onClick中加入一句：

			mSurfaceView.resetCamera();
			mGLSurfaceView.setRenderConfig(mCameraRotate, mCameraMirror);	// 加上此句，更改同步到mGLSurfaceView中
			mGLSurfaceView.getGLES2Render().setViewAngle(mCameraMirror, mCameraRotate);

**Comment by asdfqwrasdf** [comment]
请看readme
