### ISSUE TITLE
发现bug一个：操作步骤：检测识别--切换摄像头--回到桌面--回到应用--摄像头反转了

### ISSUE THREAD

**Issue by sjhsjh** [asdfqwrasdf/ArcFaceDemo#72]
解决办法：DetecterActivity的onClick中加入一句：

		mSurfaceView.resetCamera();
		mGLSurfaceView.setRenderConfig(mCameraRotate, mCameraMirror);	// 加上此句，更改同步到mGLSurfaceView中
		mGLSurfaceView.getGLES2Render().setViewAngle(mCameraMirror, mCameraRotate);

**Comment by asdfqwrasdf** [comment]
已修正，多谢！

**Comment by sjhsjh** [comment]
请问一下，你们的demo是拍照得到一张图片，然后识别一张图片的，你们demo人脸识别引擎支不支持在摄像界面实时识别人脸的？就是将RegisterActivity中线程执行的人脸识别代码放在camera每一帧的预览中执行可行不？

**Comment by asdfqwrasdf** [comment]
性能足够的话也是可行的
