### ISSUE TITLE
列表展示注册的人脸图片

### ISSUE THREAD

**Issue by LoveDarkblue** [asdfqwrasdf/ArcFaceDemo#73]
`if (!((Application)mContext.getApplicationContext()).mFaceDB.mRegister.isEmpty()) {
				FaceDB.FaceRegist face = ((Application) mContext.getApplicationContext()).mFaceDB.mRegister.get(position);
				holder.tv.setText(face.mName);
				//holder.siv.setImageResource(R.mipmap.ic_launcher);
				convertView.setWillNotDraw(false);
			}`
RegisterActivity中展示已注册人脸列表时，设置图片这一行被注释了，离线方式使用sdk的注册和检测功能，怎么展示当时注册的人脸图片呢？

**Comment by asdfqwrasdf** [comment]
这行只是示例代码，在注册成功超过1人之后，当时注册的信息会在注册页面显示，但不会显示人脸的缩略图，欢迎提交支持这个功能的代码。

**Comment by pppplayyyy** [comment]
<img width="378" alt="default" src="https://user-images.githubusercontent.com/32874996/40275462-1711d09e-5c22-11e8-94ff-cbde444c0fae.png">
我下载代码也配置好libs文件后启动这样报错 不知道是什么原因

**Comment by asdfqwrasdf** [comment]
@pppplayyyy  请按readme 操作，有问题请另外报

**Comment by liuhuan2015** [comment]
我下载了这个demo，我也有这个需求~目前还在看。哪位朋友已经解决了这个问题呢？

**Comment by pppplayyyy** [comment]
我想请问一下我的项目是一部分功能用到了这个demo，但我把application注册到manifest里的时候，我的app就启动不起来了。我想问设置这个application是否限制了启动activity的设置，因为我app的启动页面是注册登陆而不是像demo里这样。

**Comment by pppplayyyy** [comment]
还有就是"com.guo.android_extend:android-extend:1.0.5"这个扩展包的功能是什么，有源码吗
