### ISSUE TITLE
toast error

### ISSUE THREAD

**Issue by huyawen** [asdfqwrasdf/ArcFaceDemo#75]
class com.arcsoft.sdk_demo.FaceDB: AFR_FSDK_InitialEngine fail! error code :28674

I dont know  why

**Comment by asdfqwrasdf** [comment]
you can find it in sdk document.

**Comment by huyawen** [comment]
谢谢您  我已经解决上个问题了  现在出来个新问题  用这个demo的时候  人的性别检测不到值。我用的是小米5s手机测试的。是不是手机的问题呢。

**Comment by huyawen** [comment]
晕 太粗心了 那个key多空格了  谢谢楼主了
