### ISSUE TITLE
人脸检测怎么把检测到的人脸拍照保存下来呢？

### ISSUE THREAD

**Issue by smallheart** [asdfqwrasdf/ArcFaceDemo#78]
人脸检测怎么把检测到的人脸拍照保存下来呢？

**Comment by asdfqwrasdf** [comment]
这个功能需要您自己实现

**Comment by smallheart** [comment]
思路是什么呢？完全没思路

**Comment by asdfqwrasdf** [comment]
需求分析：人脸检测怎么把检测到的人脸拍照保存下来呢？
1. 目标范围：是要保存人脸的区域呢还是整张图片？是要每一张图都保存呢还是有固定策略？
2. 目标质量：保存是否会影响功能和体验，保存图片的质量，以及性能开销和功耗？
3. 目标成本：主要考虑开发的难易程度等。
综合三点细化具体的思路。

**Comment by smallheart** [comment]
1.人脸区域保存已经实现，现在期望保存整张图片（最好是高质量图片）
2.你们的sdk中有暴露保存图片的方法吗？我暂时没有找到
3.不需要每张图片都保存，我只需像手机拍照一样：点击拍照，如果识别到人脸，就直接拍摄保存；否则就提示未检测到人脸！

**Comment by asdfqwrasdf** [comment]
1.OK
2.SDK没有类似的方法。
3.请继续细化功能。比如什么情况下才点击拍照？点击拍照之后，对焦过程中，有可能人移动，如何处理？照片保存在哪个地方？拍摄分辨率要多少？
