### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by lucklizhan** [asdfqwrasdf/ArcFaceDemo#8]
为什么到了第二部检测识别时，就说没有注册人脸呢？谢谢

**Comment by asdfqwrasdf** [comment]
@lucklizhan 没有更多信息无法判断出什么问题

**Comment by lucklizhan** [comment]
demo不是分第一步：注册人脸；第二步：检测识别吗？
第一步会调用摄像头，我拍照确认后；
操作第二部，Toast出来：没有注册人脸，请先注册

**Comment by lucklizhan** [comment]
不好意思，我操作失误造成的
