### ISSUE TITLE
菜鸟的问题

### ISSUE THREAD

**Issue by blackbridcn** [asdfqwrasdf/ArcFaceDemo#80]
在demo中的android_extend的lib应该也是贵公司某位大佬写的吧，在android_extend的CameraSurfaceView类的onPreviewFrame相机预览回调方法中：` 
 CameraFrameData imageData = mImageDataBuffers.poll();
            if (imageData != null) {
                byte[] buffer = imageData.mData;
                System.arraycopy(data, 0, buffer, 0, buffer.length);
                if (mOnCameraListener != null) {
                    imageData.mParams = mOnCameraListener.onPreview(buffer, mWidth, mHeight, mFormat, timestamp);
                }
                mGLSurfaceView.requestRender(imageData);
            }`中copy相机data数据是相当于`imageData.setData(data);`吧，那为啥不直接写成imageData.setData(data);`反而用跟耗时耗力的System.arraycopy呢` 
 CameraFrameData imageData = mImageDataBuffers.poll();
            if (imageData != null) {
                imageData.setData(data);
                if (mOnCameraListener != null) {
                    imageData.mParams = mOnCameraListener.onPreview(data, mWidth, mHeight, mFormat, timestamp);
                }
                mGLSurfaceView.requestRender(imageData);
            }，上面那样呢是防止数据data被修改嘛？

**Comment by asdfqwrasdf** [comment]
是的
