### ISSUE TITLE
怎么避免你们的库被混淆了

### ISSUE THREAD

**Issue by huyawen** [asdfqwrasdf/ArcFaceDemo#84]
我现在打的包是加混淆的  加入你们的包 我加入避免混淆的代码了 但是还是找不到了。我去掉代码混淆的设置就可以找到了。看我是真么做的。希望可以提供帮助。

-keep class com.arcsoft.ageestimation.**{*;}
-keep class com.arcsoft.facedetection.**{*;}
-keep class com.arcsoft.facerecognition.**{*;}
-keep class com.arcsoft.facetracking.**{*;}
-keep class com.arcsoft.genderestimation.**{*;}

#保持第三方的.so库不能被混淆 否则调用的时候找不到
-libraryjars libs/armeabi/libArcSoft_AEEngine.so
-libraryjars libs/armeabi/libArcSoft_FDEngine.so
-libraryjars libs/armeabi/libArcSoft_FREngine.so
-libraryjars libs/armeabi/libArcSoft_FTEngine.so
-libraryjars libs/armeabi/libArcSoft_GEEngine.so
-libraryjars libs/armeabi/libmpbase.so

-libraryjars libs/armeabi-v7a/libArcSoft_AEEngine.so
-libraryjars libs/armeabi-v7a/libArcSoft_FDEngine.so
-libraryjars libs/armeabi-v7a/libArcSoft_FREngine.so
-libraryjars libs/armeabi-v7a/libArcSoft_FTEngine.so
-libraryjars libs/armeabi-v7a/libArcSoft_GEEngine.so
-libraryjars libs/armeabi-v7a/libmpbase.so

不知道为什么 还是混淆掉了。

**Comment by asdfqwrasdf** [comment]
#22 
#23 
#28 
#30 
供参考

**Comment by huyawen** [comment]
忘记混淆那个 camera的库了。现在可以了。
