### ISSUE TITLE
人脸追踪err.getCode()为2

### ISSUE THREAD

**Issue by gxh-apologize** [asdfqwrasdf/ArcFaceDemo#85]
首先Demo没有问题，我是从海康摄像头来识别人脸的，err.getCode为2，是参数无效，是宽高的问题吗？因为一直不太明白这里宽高要传什么。初涉及视频，小白一枚，希望大神回复一下，谢谢。

AFT_FSDKError err = engine.AFT_FSDK_FaceFeatureDetect(pDataBuffer, 640, 480, AFT_FSDKEngine.CP_PAF_NV21, result);
        Log.d(TAG, "AFT_FSDK_FaceFeatureDetect =" + err.getCode());
        Log.d(TAG, "Face=" + result.size());

**Comment by asdfqwrasdf** [comment]
这里的代码看上去没啥问题

**Comment by gxh-apologize** [comment]
是pDataBuffer的格式的问题，现在已解决。谢谢回答！
