### ISSUE TITLE
可已联系一下吗 我有些问题需要咨询

### ISSUE THREAD

**Issue by huyawen** [asdfqwrasdf/ArcFaceDemo#91]
你加我qq 1754397982   或者 我加你qq度可以

**Comment by asdfqwrasdf** [comment]
demo 的issue 直接这里提，sdk问题请找官方群

**Comment by meiyouxiaoxiongle** [comment]
我用eclipse导入的这个项目，项目报错 都已解决，但是还是在运行注册时打开图片和拍摄图片时都会闪退，这是什么问题

**Comment by huyawen** [comment]
那个摄像头预览的 我想改为圆形预览 。但是改完以后没有生效。想问问 楼主知道原因吗CameraSurfaceView 这个是预览的类 我继承这个类
  private int height; // 圆的半径

    public MyCameraSurfaceView(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
    }

    public MyCameraSurfaceView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public MyCameraSurfaceView(Context context) {
        super(context);
    }


    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);

        int widthMode = MeasureSpec.getMode(widthMeasureSpec);
        int heightMode = MeasureSpec.getMode(heightMeasureSpec);
        int widthSize = MeasureSpec.getSize(widthMeasureSpec);
        int heightSize = MeasureSpec.getSize(heightMeasureSpec);

        height = widthSize;
        Log.e("onMeasure", "draw: widthMeasureSpec = " + widthSize + "  heightMeasureSpec = " + heightSize);
        setMeasuredDimension(widthSize, heightSize);

    }

    @Override
    public void draw(Canvas canvas) {
        Log.e("onDraw", "draw: test");
        Path path = new Path();
        path.addCircle(height / 2, height / 2, height / 2, Path.Direction.CCW);
        canvas.clipPath(path, Region.Op.REPLACE);
        super.draw(canvas);
    }


    @Override
    protected void onDraw(Canvas canvas) {
        Log.e("onDraw", "onDraw");
        super.onDraw(canvas);
    }

重写了这个方法  但是预览效果还是矩形，。

**Comment by huyawen** [comment]
就是按照网上的方法  重写了 draw()方法 和onMeasure方法

**Comment by gqjjqg** [comment]
第三方插件功能请先了解一下，这个view不是用来显示的，如要修改请先查阅源码。crop圆形可以opengl做，或者加mask。 在2018年07月19日 15:54 ，hello java写道： 就是按照网上的方法 重写了 draw()方法 和onMeasure方法 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by asdfqwrasdf** [comment]
非demo 问题和功能需求
