### ISSUE TITLE
针对安卓外接的USB摄像头是否支持呢？

### ISSUE THREAD

**Issue by cayden** [asdfqwrasdf/ArcFaceDemo#99]
Hi,
         您好，近日使用了贵公司的产品，挺好的，但是想咨询一下，是否对安卓外接USB的摄像头支持呢？demo是主要针对手机自带的前置和后置摄像头。
         谢谢！！！

**Comment by asdfqwrasdf** [comment]
支持外接camera走android 系统流程。
不支持单独走的UVC方式，有smaple code 需要自行修改

**Comment by cayden** [comment]
这个smaple code 有链接吗，谢谢！

**Comment by asdfqwrasdf** [comment]
可以参考这个：[Link](https://github.com/gqjjqg/samples/blob/master/src/main/src/com/guo/samples/VideoActivity.java)

**Comment by cayden** [comment]
好的 谢谢！
